apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  namespace: friha-exo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: 10Gi
