apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
    app: wordpress
  name: mysql
  namespace: friha-exo
spec:
  containers:
  - image: mysql:5.6
    name: mysql
    envFrom:
      - secretRef:
          name: mysql-secret
    resources: {}
    volumeMounts:
    - name: disk
      mountPath : "/var/lib/mysql"
  volumes:
    - name: disk
      persistentVolumeClaim:
        claimName: azuredisk
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
