apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azuredisk
  namespace: friha-exo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 60Gi
