apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-srv
  name: mysql-srv
  namespace: friha-exo
spec:
  ports:
  - name: sql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    run: mysql
    app: wordpress
  type: ClusterIP
